export const base = {
  FONT_SIZE_TINY: 8,
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 16,
  FONT_SIZE_LARGE: 20,
  FONT_SIZE_EXTRA_LARGE: 24,
  FONT_SIZE_MASSIVE: 34,

  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_MEDIUM: '500',
  FONT_WEIGHT_BOLD: '700',

  PRIMARY_FONT_FAMILY: 'XMYekan',
  PRIMARY_FONT_FAMILY_BOLD: 'XMYekan-Bold',

  SECONDARY_FONT_FAMILY: 'XBRoya',
  SECONDARY_FONT_FAMILY_BOLD: 'XBRoya-Bold',

  MAIN_FONT_SIZE: 16
}

export const darkTheme = {
  PRIMARY_BACKGROUND_COLOR: '#3d3d3d',
  PRIMARY_BACKGROUND_COLOR_LIGHT: '#797979',

  SECONDARY_BACKGROUND_COLOR: '#ffffff',
  SECONDARY_BACKGROUND_COLOR_LIGHT: '#f7f7f7',

  PRIMARY_TEXT_COLOR: '#ffffff',
  PRIMARY_TEXT_COLOR_LIGHT: '#f7f7f7',
  SECONDARY_TEXT_COLOR: '#3d3d3d',
  PRIMARY_TEXT_BACKGROUND_COLOR: '#3d3d3d',
  SECONDARY_TEXT_BACKGROUND_COLOR: '#ffffff',
}
export const lightTheme = {
  PRIMARY_BACKGROUND_COLOR: '#ffffff',
  PRIMARY_BACKGROUND_COLOR_LIGHT: '#f7f7f7',

  SECONDARY_BACKGROUND_COLOR: '#3d3d3d',
  SECONDARY_BACKGROUND_COLOR_LIGHT: '#797979',

  PRIMARY_TEXT_COLOR: '#3d3d3d',
  PRIMARY_TEXT_COLOR_LIGHT: '#797979',
  SECONDARY_TEXT_COLOR: '#ffffff',
  PRIMARY_TEXT_BACKGROUND_COLOR: '#ffffff',
  SECONDARY_TEXT_BACKGROUND_COLOR: '#3d3d3d',
}


export const colorOptions = {
  orange: {
    PRIMARY_COLOR_FAINT: '#FFF3E0',
    PRIMARY_COLOR_LIGHT: '#FFB74D',
    PRIMARY_COLOR: '#FF9800',
    PRIMARY_COLOR_BOLD: '#EF6C00',
    PRIMARY_FOREGROUND_COLOR: '#ffffff',
  },
  red: {
    PRIMARY_COLOR_FAINT: '#FFEBEE',
    PRIMARY_COLOR_LIGHT: '#E57373',
    PRIMARY_COLOR: '#F44336',
    PRIMARY_COLOR_BOLD: '#C62828',
    PRIMARY_FOREGROUND_COLOR: '#ffffff',
  },
  blue: {
    PRIMARY_COLOR_FAINT: '#E3F2FD',
    PRIMARY_COLOR_LIGHT: '#64B5F6',
    PRIMARY_COLOR: '#2196F3',
    PRIMARY_COLOR_BOLD: '#1565C0',
    PRIMARY_FOREGROUND_COLOR: '#ffffff',
  },
  cyan: {
    PRIMARY_COLOR_FAINT: '#E0F7FA',
    PRIMARY_COLOR_LIGHT: '#4DD0E1',
    PRIMARY_COLOR: '#00BCD4',
    PRIMARY_COLOR_BOLD: '#00838F',
    PRIMARY_FOREGROUND_COLOR: '#ffffff',
  },
  teal: {
    PRIMARY_COLOR_FAINT: '#E0F2F1',
    PRIMARY_COLOR_LIGHT: '#4DB6AC',
    PRIMARY_COLOR: '#009688',
    PRIMARY_COLOR_BOLD: '#00695C',
    PRIMARY_FOREGROUND_COLOR: '#ffffff',
  },
  gray: {
    PRIMARY_COLOR_FAINT: '#FAFAFA',
    PRIMARY_COLOR_LIGHT: '#E0E0E0',
    PRIMARY_COLOR: '#9E9E9E',
    PRIMARY_COLOR_BOLD: '#424242',
    PRIMARY_FOREGROUND_COLOR: '#ffffff',
  },
  purple: {
    PRIMARY_COLOR_FAINT: '#EDE7F6',
    PRIMARY_COLOR_LIGHT: '#9575CD',
    PRIMARY_COLOR: '#673AB7',
    PRIMARY_COLOR_BOLD: '#4527A0',
    PRIMARY_FOREGROUND_COLOR: '#ffffff',
  },
  green: {
    PRIMARY_COLOR_FAINT: '#E8F5E9',
    PRIMARY_COLOR_LIGHT: '#81C784',
    PRIMARY_COLOR: '#4CAF50',
    PRIMARY_COLOR_BOLD: '#2E7D32',
    PRIMARY_FOREGROUND_COLOR: '#ffffff',
  },
}


export const colorOptionsSecondary = {
  orange: {
    SECONDARY_COLOR_FAINT: '#FFF3E0',
    SECONDARY_COLOR_LIGHT: '#FFB74D',
    SECONDARY_COLOR: '#FF9800',
    SECONDARY_COLOR_BOLD: '#EF6C00',
    SECONDARY_FOREGROUND_COLOR: '#ffffff',
  },
  red: {
    SECONDARY_COLOR_FAINT: '#FFEBEE',
    SECONDARY_COLOR_LIGHT: '#E57373',
    SECONDARY_COLOR: '#F44336',
    SECONDARY_COLOR_BOLD: '#C62828',
    SECONDARY_FOREGROUND_COLOR: '#ffffff',
  },
  blue: {
    SECONDARY_COLOR_FAINT: '#E3F2FD',
    SECONDARY_COLOR_LIGHT: '#64B5F6',
    SECONDARY_COLOR: '#2196F3',
    SECONDARY_COLOR_BOLD: '#1565C0',
    SECONDARY_FOREGROUND_COLOR: '#ffffff',
  },
  cyan: {
    SECONDARY_COLOR_FAINT: '#E0F7FA',
    SECONDARY_COLOR_LIGHT: '#4DD0E1',
    SECONDARY_COLOR: '#00BCD4',
    SECONDARY_COLOR_BOLD: '#00838F',
    SECONDARY_FOREGROUND_COLOR: '#ffffff',
  },
  teal: {
    SECONDARY_COLOR_FAINT: '#E0F2F1',
    SECONDARY_COLOR_LIGHT: '#4DB6AC',
    SECONDARY_COLOR: '#009688',
    SECONDARY_COLOR_BOLD: '#00695C',
    SECONDARY_FOREGROUND_COLOR: '#ffffff',
  },
  gray: {
    SECONDARY_COLOR_FAINT: '#FAFAFA',
    SECONDARY_COLOR_LIGHT: '#E0E0E0',
    SECONDARY_COLOR: '#9E9E9E',
    SECONDARY_COLOR_BOLD: '#424242',
    SECONDARY_FOREGROUND_COLOR: '#ffffff',
  },
  purple: {
    SECONDARY_COLOR_FAINT: '#EDE7F6',
    SECONDARY_COLOR_LIGHT: '#9575CD',
    SECONDARY_COLOR: '#673AB7',
    SECONDARY_COLOR_BOLD: '#4527A0',
    SECONDARY_FOREGROUND_COLOR: '#ffffff',
  },
  green: {
    SECONDARY_COLOR_FAINT: '#E8F5E9',
    SECONDARY_COLOR_LIGHT: '#81C784',
    SECONDARY_COLOR: '#4CAF50',
    SECONDARY_COLOR_BOLD: '#2E7D32',
    SECONDARY_FOREGROUND_COLOR: '#ffffff',
  },
}
