export const SET_DATABASE = 'SET_DATABASE'

export const CHANGE_MAIN_FONT_SIZE = 'CHANGE_MAIN_FONT_SIZE'
export const CHANGE_PRIMARY_COLOR = 'CHANGE_PRIMARY_COLOR'
export const CHANGE_THEME_BACKGROUND = 'CHANGE_THEME_BACKGROUND'